### ISSUE TITLE
Incorrect AV pack constants lead to crash on PAL-Xbox

### ISSUE THREAD

**Issue by thrimbor** [xqemu/nxdk#22]
I found this while investigating why all the nxdk-samples make my Xbox (PAL, 1.0 I think since it used to have that GPU-fan) lock up.

I fired up my Debug-BIOS, which showed that somewhere in the code, MmAllocateContiguousMemoryEx was called with a size-parameter of zero, which triggers an assertion in the kernel. I managed to track down this allocation to [line 3489 of pbkit.c](https://github.com/xqemu/nxdk/blob/master/lib/pbkit/pbkit.c#L3489). Further investigation showed that no videomode was set, and neither pb_init() nor XboxCRT() handle that case. I dug in the video-code and found out that no mode was set because all were rejected based on my AV pack - the constants go up to 5, my Xbox reports a 6. Removing that check (not a clean solution) resolved that for me, and the httpd-sample stopped crashing and worked nicely (didn't test others yet).

So the AV-pack constants that nxdk has seem to be incomplete. I managed to get my hands on a list of constants the kernel uses for them, which is the following:
```
#define AV_PACK_NONE                      0x00000000
#define AV_PACK_STANDARD                  0x00000001
#define AV_PACK_RFU                       0x00000002
#define AV_PACK_SCART                     0x00000003
#define AV_PACK_HDTV                      0x00000004
#define AV_PACK_VGA                       0x00000005
#define AV_PACK_SVIDEO                    0x00000006
#define AV_PACK_MAX                       0x00000007
#define AV_PACK_MASK                      0x000000FF
```
These differ a bit from the ones nxdk uses. Interestingly, these constants claim that my AV pack is SVIDEO, but it's a standard composite-one.

To resolve this, I'd suggest that pb_init() gets a check for a set video-mode. However, I'm not sure about what exactly to do about the constant-issue, which is the core-problem.

**Comment by JayFoxRox** [comment]
Interesting, apparently someone used the modes as transmitted by the SMC, not the actual constants of the av* kernel portion.

There is a function doing the remapping in the kernel when calling `AvSendTVEncoderOption` with `Option = AV_QUERY_AV_CAPABILITIES` (Value 6). The remapping is done in the first function being called by the handler function. There is some more logic afterwards in the calling function so I did not check if the return value of `AvSendTVEncoderOption` still contains the re-mapped value. The result of `AvSendTVEncoderOption` also seems to depend on the eeprom region value.
So maybe we should use said function?

---

Here is what the non-exported function does (it's very short and only does this mapping). I've replaced the av* side with your constants:

* 0: AV_PACK_SCART
* 1: AV_PACK_HDTV
* 2: AV_PACK_VGA
* 3: AV_PACK_RFU
* 4: AV_PACK_SVIDEO
* 6: AV_PACK_STANDARD
* else: AV_PACK_NONE

(Note the lack of mode 5)

This also seems to match the data available at http://www.gamesx.com/avpinouts/xbox.htm (read in reverse, blue = 0 / black = 1)
* SCART is listed as 000 = 0 (AV_PACK_SCART)
* Component is listed as 100 -> 001 = 1 (AV_PACK_HDTV)
* VGA is listed as 010 = 2 (AV_PACK_VGA)
* NTSC Mono is listed as 110 -> 011 = 3 (AV_PACK_RFU)
* PAL Stereo is listed as 001 -> 100 = 4 (AV_PACK_SVIDEO)
* PAL/Secam Mono is listed as 101 = 5 (AV_PACK_NONE) *Presumably AV Pack does not exist?*
* NTSC Stereo is listed as 011 -> 110 = 6 (AV_PACK_STANDARD)
* "-" is listed as 111 = 7 (AV_PACK_NONE)

---

I'll probably move the contents of that website and the AV SMC to kernel av* logic to the wiki tonight or tomorrow.

**Comment by JayFoxRox** [comment]
@thrimbor I have now completed http://xboxdevwiki.net/AV_Cables

If possible, please make a photo of your AV-Cable (if it is an original Microsoft product). Also compare against the original Microsoft **NTSC** S-Video product. However, I'm assuming you did not import it, so it's probably not an official Microsoft cable (in which case, don't bother with the photo).

I assume that the 3rd party vendors didn't care what their cable identifies as. A cable of type 6, might also identify as 0, 1 or 2. All of those will carry V, C, Y signals. Audio wise 0 and 2 are mono; but 1 and 6 are stereo. However, I'm not even sure if the audio mono/stereo is switched in hardware, or simply not connected by the cable.

I'm not sure if the cable type still has any implications for the kernel-chosen resolution / video mode, even if the signal standard is the same.

---

If my wiki table is correct, we could generate new constant names. However, in my opinion we can also re-use the Microsoft constants (which appear in various public places anyway).

**Comment by JayFoxRox** [comment]
As for the modes in the video.c: See list below

I list conclusions and hints as to why I think they have to be like I suggest in the braces. I did not change the actual code, just annotated each group with the correct pack / mode.

---


AV_PACK_STANDARD (V,C,Y):

```
 {0x44030307,640,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_COMPOSITE}, //640x480 PAL 50Hz
 {0x44040408,720,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_COMPOSITE}, //720x480 PAL 50Hz
 {0x0401010B,640,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_COMPOSITE}, //640x480 PAL 60Hz
 {0x0402020C,720,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_COMPOSITE}, //720x480 PAL 60Hz
 {0x04010101,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_COMPOSITE}, //640x480 NTSCM 60Hz
 {0x04020202,720,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_COMPOSITE}, //720x480 NTSCM 60Hz
 {0x04010103,640,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_COMPOSITE}, //640x480 NTSCJ 60Hz
 {0x04020204,720,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_COMPOSITE}, //720x480 NTSCJ 60Hz
```

AV_PACK_SVIDEO (same modes as STANDARD, so it must be something V,C,Y):

```
 {0x44030307,640,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_RCA}, //640x480 PAL 50Hz
 {0x44040408,720,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_RCA}, //720x480 PAL 50Hz
 {0x0401010B,640,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_RCA}, //640x480 PAL 60Hz
 {0x0402020C,720,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_RCA}, //720x480 PAL 60Hz
 {0x04010101,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_RCA}, //640x480 NTSCM 60Hz
 {0x04020202,720,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_RCA}, //720x480 NTSCM 60Hz
 {0x04010103,640,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_RCA}, //640x480 NTSCJ 60Hz
 {0x04020204,720,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_RCA}, //720x480 NTSCJ 60Hz
```

AV_PACK_RFU (same modes as STANDARD, so it must be something V,C,Y):

```
 {0x44030307,640,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_SVIDEO}, //640x480 PAL 50Hz
 {0x44040408,720,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_SVIDEO}, //720x480 PAL 50Hz
 {0x0401010B,640,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_SVIDEO}, //640x480 PAL 60Hz
 {0x0402020C,720,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_SVIDEO}, //720x480 PAL 60Hz
 {0x04010101,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_SVIDEO}, //640x480 NTSCM 60Hz
 {0x04020202,720,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_SVIDEO}, //720x480 NTSCM 60Hz
 {0x04010103,640,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_SVIDEO}, //640x480 NTSCJ 60Hz
 {0x04020204,720,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_SVIDEO}, //720x480 NTSCJ 60Hz
```

AV_PACK_SCART (Comments list this as RGB signal):

```
 {0x60030307,640,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_RGBSCART}, //640x480 PAL 50Hz RGB
 {0x60040408,720,480,50,VIDEO_REGION_PAL,VIDEO_ADAPTER_RGBSCART}, //720x480 PAL 50Hz RGB
 {0x2001010B,640,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_RGBSCART}, //640x480 PAL 60Hz RGB
 {0x2002020C,720,480,60,VIDEO_REGION_PAL,VIDEO_ADAPTER_RGBSCART}, //720x480 PAL 60Hz RGB
 {0x20010101,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_RGBSCART}, //640x480 NTSCM 60Hz RGB
 {0x20020202,720,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_RGBSCART}, //720x480 NTSCM 60Hz RGB
 {0x20010103,640,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_RGBSCART}, //640x480 NTSCJ 60Hz RGB
 {0x20020204,720,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_RGBSCART}, //720x480 NTSCJ 60Hz RGB
```

AV_PACK_HDTV (Contains 1080i):

```
 {0x88070701,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_HDTV}, //640x480p NTSCM 60Hz
 {0x88080801,720,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_HDTV}, //720x480p NTSCM 60Hz
 {0x880B0A02,1280,720,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_HDTV}, //1280x720p NTSCM 60Hz
 {0x880E0C03,1920,1080,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_HDTV}, //1920x1080i NTSCM 60Hz
 {0x88070701,640,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_HDTV}, //640x480p NTSCJ 60Hz
 {0x88080801,720,480,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_HDTV}, //720x480p NTSCJ 60Hz
 {0x880B0A02,1280,720,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_HDTV}, //1280x720p NTSCJ 60Hz
 {0x880E0C03,1920,1080,60,VIDEO_REGION_NTSCJ,VIDEO_ADAPTER_HDTV}, //1920x1080i NTSCJ 60Hz
```

AV_PACK_VGA (VGA resolutions):

```
 {0xC0060601,640,480,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_VGA_SOG}, //640x480 SVGA 60Hz
 {0xC0030303,800,600,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_VGA_SOG}, //800x600 SVGA 60Hz
 {0xC0040404,1024,768,60,VIDEO_REGION_NTSCM,VIDEO_ADAPTER_VGA_SOG}, //1024x768 SVGA 60Hz
```

---

Note that the mode search functions in video.c always check the adapter first (unless I missed something). As a result the actual ordering does not matter. We should probably re-order them to reflect the actual order of AV_PACK constants.

*(I did not verify if the actual modes in the modelist were correct to begin with - but for now, let's assume their list is fine)*
